[versions]
xapi = '0.5.1'
gdx = '2.13.2-SNAPSHOT'
swt = '4.5.1'
gwt = '2.8.0'
elemental = '1.1.0'
jbox2d = '2.2.1.1'
robovm = '2.3.18'
android = '30'
android-plugin = '8.5.2'
android-kotlin = '1.5.31'
j2objc-plugin = '0.7.1'
spock = '2.3-groovy-4.0'
junit = '4.13.2'
quarkus = '3.6.4'

[libraries]


xapi-fu = { module = "net.wti.core:xapi-fu", version.ref = "xapi" }
xapi-gen = { module = "net.wti.core:xapi-gen", version.ref = "xapi" }
xapi-lang-core = { module = "net.wti.core:xapi-lang-core", version.ref = "xapi" }

xapi-lang-dev = { module = "net.wetheinter:xapi-dev-lang", version.ref = "xapi" }
xapi-inject = { module = "net.wetheinter:xapi-inject", version.ref = "xapi" }
xapi-inject-api = { module = "net.wetheinter:xapi-inject-api", version.ref = "xapi" }
xapi-inject-jre = { module = "net.wetheinter:xapi-inject-jre", version.ref = "xapi" }
xapi-inject-gwt = { module = "net.wetheinter:xapi-inject-gwt", version.ref = "xapi" }
xapi-log-api = { module = "net.wetheinter:xapi-log-api", version.ref = "xapi" }
xapi-io = { module = "net.wetheinter:xapi-io", version.ref = "xapi" }
xapi-io-gwt = { module = "net.wetheinter:xapi-io-gwt", version.ref = "xapi" }
xapi-io-jre = { module = "net.wetheinter:xapi-io-jre", version.ref = "xapi" }
xapi-core-event = { module = "net.wetheinter:xapi-core-event", version.ref = "xapi" }
xapi-common = { module = "net.wetheinter:xapi-base", version.ref = "xapi" }
xapi-common-api = { module = "net.wetheinter:xapi-base-api", version.ref = "xapi" }
xapi-common-spi = { module = "net.wetheinter:xapi-base-spi", version.ref = "xapi" }
xapi-common-gwt = { module = "net.wetheinter:xapi-base-gwt", version.ref = "xapi" }
xapi-elemental = { module = "net.wetheinter:xapi-gwt3", version.ref = "xapi" }
elemental = { module = "com.google.elemental2:elemental2-dom", version.ref = "elemental" }
xapi-model = { module = "net.wetheinter:xapi-model", version.ref = "xapi" }
xapi-model-api = { module = "net.wetheinter:xapi-model-api", version.ref = "xapi" }
xapi-model-jre = { module = "net.wetheinter:xapi-model-jre", version.ref = "xapi" }
xapi-model-gwt = { module = "net.wetheinter:xapi-model-gwt", version.ref = "xapi" }
xapi-util = { module = "net.wetheinter:xapi-util", version.ref = "xapi" }
xapi-core-args = { module = "net.wetheinter:xapi-core-args", version.ref = "xapi" }
xapi-core-ui-api = { module = "net.wetheinter:xapi-core-ui-api", version.ref = "xapi" }
xapi-ui-api = { module = "net.wetheinter:xapi-ui-api", version.ref = "xapi" }
xapi-dev-bytecode = { module = "net.wetheinter:xapi-dev-bytecode", version.ref = "xapi" }
xapi-dev-file = { module = "net.wetheinter:xapi-dev-file", version.ref = "xapi" }
xapi-server-api = { module = "net.wetheinter:xapi-server-api", version.ref = "xapi" }
xapi-collect-main = { module = "net.wetheinter:xapi-collect", version.ref = "xapi" }
xapi-collect-api = { module = "net.wetheinter:xapi-collect-api", version.ref = "xapi" }
xapi-collect-gwt = { module = "net.wetheinter:xapi-collect-gwt", version.ref = "xapi" }

gwt-dev = { module = "net.wetheinter:gwt-dev", version.ref = "gwt" }
gwt-user = { module = "net.wetheinter:gwt-user", version.ref = "gwt" }

spock = { module = "org.spockframework:spock-core", version.ref = "spock" }
junit = { module = "junit:junit", version.ref = "junit" }

gdx-core = { module = "com.badlogicgames.gdx:gdx", version.ref = "gdx" }
gdx-platform = { module = "com.badlogicgames.gdx:gdx-platform", version.ref = "gdx" }
gdx-backend-headless = { module = "com.badlogicgames.gdx:gdx-backend-headless", version.ref = "gdx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "android-kotlin" }
ios-plugin = { id = "net.socialhub.j2objccontrib.j2objcgradle", version.ref = "j2objc-plugin" }
xapi-plugin = { id = "xapi-require", version.ref = "xapi" }
